-- AlterTable
ALTER TABLE `user` ADD COLUMN `itemsPaidFor` INTEGER NULL DEFAULT 0,
    ADD COLUMN `lodgesPaidFor` INTEGER NULL DEFAULT 0,
    ADD COLUMN `roomsPaidFor` INTEGER NULL DEFAULT 0,
    ADD COLUMN `servicesPaidFor` INTEGER NULL DEFAULT 0;
